#!/usr/bin/env bash

cd /home/nbr/Documentos/NixOs-Conf

# Formatea
echo "Corrigiendo formato..."
find . -name "*.nix" -exec nixfmt {} \;

# Actualiza pass
pass git pull
pass git push

# Actualiza Flak
echo "Actualizando flake..."
echo "Desactivado temporalmente"
# nix flake update

# Pushea git
echo "Pusheando a git..."
git add *
git commit -m "commit autogenerated when updating"
git push origin main

# Realiza el switch
echo "Reconstruyendo el sistema..."
sudo nixos-rebuild switch --flake .
home-manager switch --flake . --impure

echo "Eliminando copias antiguas del sistema..."

nix-collect-garbage --delete-older-than 10d

echo "¡Pipeline finalizada!"

